### PR TITLE
Hack: Work around unpublished modules

### LINKED ISSUE #6: Some dependencies have been unpublished
The following packages have been unpublished by the auther and replaced by NPM with placeholders
- dom-style
- dom-tree
- dom-value
- dom-select

Only dom-select appears to be used right now, but the others are also referenced by the package.json, so `npm install` is failing right now.

### PR DESCRIPTION
**Pull request by nschonni**
Inlined `dom-select` and `new-element`
Shuffled dependencies with `nom-check`

---

Sinon includes were because the Atom eslint plugin was bugging me.

Works on my machine :tm: 

Fixes #6

### CODE REVIEW

File: test/ext/new-element.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// From https://github.com/npm-dom/new-element
+
+var domify = require("domify");
```
Comment (jessebeach) [inline test/ext/new-element.js:3]: Please use `const` instead of `var` for all module assignments. We should never be altering module objects.

File: test/ext/new-element.js [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+var format = require("./format-text");
+
+module.exports = newElement;
+
+function newElement (html, vars) {
+  if (arguments.length == 1) return domify(html);
```
Comment (jessebeach) [inline test/ext/new-element.js:9]: Brackets on the `if` block please.

File: test/ext/format-text.js [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  return function (tag, name) {
+    if (tag.substring(0, 2) == '{{' && tag.substring(tag.length - 2) == '}}') {
+      return '{' + name + '}';
+    }
+
+    if (!context.hasOwnProperty(name)) {
+      return tag;
+    }
+
+    if (typeof context[name] == 'function') {
```
Comment (jessebeach) [inline test/ext/format-text.js:27]: triple equals

File: test/ext/format-text.js [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+  } else {
+    context = Array.prototype.slice.call(arguments, 1);
+  }
+
+  return String(text).replace(/\{?\{([^{}]+)}}?/g, replace(context));
+};
+
+function replace (context, nil){
+  return function (tag, name) {
+    if (tag.substring(0, 2) == '{{' && tag.substring(tag.length - 2) == '}}') {
```
Comment (jessebeach) [inline test/ext/format-text.js:19]: I like to put each condition on its own line for clarity e.g.:

```
if (
  tag.substring(0, 2) == '{{' && 
  tag.substring(tag.length - 2) == '}}'
) {
```

Also, triple equals.

**Comment by nschonni** [comment]
I'll try and take a look at the comments this weekend, but note that the files in `ext` are direct copy/paste from the unpublished modules.

**Comment by jessebeach** [comment]
The changes looks good, just a few style issues.

**Comment by jessebeach** [comment]
Gotcha, then just make sure that the `ext` dir isn't being scanned by the linters.

**Comment by nschonni** [comment]
Yup, I noticed that nothing in the test directory gets scanned right now https://github.com/quailjs/quail-core/blob/master/package.json#L61-L62
I'll probably look at turning on the linting in `test` in another PR

**Comment by nschonni** [comment]
Although it is on for watch https://github.com/quailjs/quail-core/blob/master/package.json#L72-L78
